<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>chatClient</title>
        <link href='//fonts.googleapis.com/css?family=Gloria+Hallelujah' rel='stylesheet' type='text/css'>
        <!-- Angular -->
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.6/angular.min.js"></script>
        <script src="../public/app.js"></script>
        <!-- Bootstrap -->
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="../public/main.css">
    </head>
    <body>
        <h1>chatClient</h1>
        <div>an embeddable chat client in angular and php</div>
        <div class="container" ng-app="chatApp" ng-controller="ChatController">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h6 class="panel-title">Please enter your name.</h6>
            </div>
            <div class="panel-body">
              <div class="input-group">
                <input type="text" class="form-control" ng-model="adminName" placeholder="Name" aria-describedby="basic-addon1">
              </div>
              <button type="button" ng-click="addAdmin()" class="btn btn-primary btn-lg">Get chattin'</button>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              &nbsp;
            </div>
          </div>
          <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
              <div class="row">
                <div class="col-md-12">
                  <div class="panel panel-primary">
                    <div class="panel-heading" style="padding:0 0 0 8px;">
                      <span class="glyphicon glyphicon-user"></span>
                      <h6 class="panel-title" style="display:inline;">Rep Chat</h6>
                      <div class="btn-group btn-group-xs pull-right">
                        <button type="button" class="btn btn-primary"><span class="glyphicon glyphicon-remove"></span></button>
                      </div>
                      <div class="clearfix"></div>
                    </div>
                    <div class="panel-body" style="padding:0 4px;">
                      <div class="row">
                        <div class="col-xs-12 scroll-div" style="max-height:300px;max-width:100%;overflow-y:auto;overflow-x:hidden;">
                          <table class="table table-hover table-condensed">
                            <tr ng-hide="chatMessages.length === 0" ng-repeat="chat in chatMessages | orderBy:origDt | reverse"
                                style="min-width:100%;max-width:100%;width:100%;">
                              <td>
                                <h6>{{chat.username}}</h6>
                              </td>
                              <td>
                              <p class="word-wrap:break-word"><small>{{chat.text}}</small></p>
                              </td>
                            </tr>
                            <tr ng-show="chatMessages.length === 0">
                              <td>
                                <p>Nothin' here. <strong>Say something!</strong></p>
                              </td>
                            </tr>
                          </table>
                        </div>
                      </div>
                    </div>
                    <div class="panel-footer">
                      <form>
                        <div class="input-group input-group-sm">
                          <span class="input-group-addon">
                            <img src="http://placehold.it/16x16" alt="" />
                          </span>
                          <input type="text" class="form-control" ng-model="newChatMsg" placeholder="..."/>
                          <span class="input-group-btn">
                            <button class="btn btn-primary" type="submit" ng-click="addChat()">Send</button>
                          </span>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-4"></div>
          </div>
        </div>
    </body>
</html>
