<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>chatClient</title>
        <link href='//fonts.googleapis.com/css?family=Gloria+Hallelujah' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Gloria Hallelujah', cursive;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1>chatClient</h1>
        <div>an embaddable chat client in angular and php</div>
        <br>
        <div>to test, open the chat window below. Then, click <a href="/">here</a> to chat back.</div>
        <br>
        <div>view on <a href="https://github.com/blakeprobinson/chatClient">github</a></div>
        <?php if (isset($name)) : ?>
            <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
        <?php else: ?>
            <p>Try <a href="http://www.slimframework.com">SlimFramework</a>
        <?php endif; ?>
    </body>
</html>
